from . import db

class SpecialPlan(db.Model):
    __tablename__ = 'school_special_plan'
    id = db.Column(db.Integer, primary_key=True)
    batch_type = db.Column(db.String)
    year = db.Column(db.Integer)
    school_id = db.Column(db.Integer)
    special_id = db.Column(db.Integer)
    type = db.Column(db.String)
    batch = db.Column(db.String)
    num = db.Column(db.Integer)
    zslx = db.Column(db.String)
    province = db.Column(db.String)
    length = db.Column(db.String)
    tuition = db.Column(db.String)
    spe_id = db.Column(db.String)
    info = db.Column(db.String)
    special_group = db.Column(db.String)
    first_km = db.Column(db.String)
    sp_type = db.Column(db.String)
    sp_fxk = db.Column(db.String)
    sp_sxk = db.Column(db.String)
    sp_info = db.Column(db.String)
    sp_xuanke = db.Column(db.String)
    level1_name = db.Column(db.String)
    level2_name = db.Column(db.String)
    level3_name = db.Column(db.String)
    level1 = db.Column(db.String)
    level2 = db.Column(db.String)
    level3 = db.Column(db.String)
    spcode = db.Column(db.String)
    spname = db.Column(db.String)
    local_batch_name = db.Column(db.String)
    zslx_name = db.Column(db.String)
    sg_fxk = db.Column(db.String)
    sg_sxk = db.Column(db.String)
    sg_type = db.Column(db.String)
    sg_name = db.Column(db.String)
    sg_info = db.Column(db.String)
    sg_xuanke = db.Column(db.String)

    def as_dict(self):
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}

class SpecialScore(db.Model):
    __tablename__ = 'school_special_score'
    id = db.Column(db.Integer, primary_key=True)
    batch_type = db.Column(db.String)
    year = db.Column(db.Integer)
    school_id = db.Column(db.Integer)
    special_id = db.Column(db.Integer)
    type = db.Column(db.String)
    batch = db.Column(db.String)
    zslx = db.Column(db.String)
    max = db.Column(db.Float)
    min = db.Column(db.Float)
    average = db.Column(db.Float)
    min_section = db.Column(db.String)
    province = db.Column(db.String)
    spe_id = db.Column(db.String)
    info = db.Column(db.String)
    special_group = db.Column(db.String)
    first_km = db.Column(db.String)
    sp_type = db.Column(db.String)
    sp_fxk = db.Column(db.String)
    sp_sxk = db.Column(db.String)
    sp_info = db.Column(db.String)
    sp_xuanke = db.Column(db.String)
    is_score_range = db.Column(db.String)
    min_range = db.Column(db.String)
    min_rank_range = db.Column(db.String)
    level1_name = db.Column(db.String)
    level2_name = db.Column(db.String)
    level3_name = db.Column(db.String)
    level1 = db.Column(db.String)
    level2 = db.Column(db.String)
    level3 = db.Column(db.String)
    spname = db.Column(db.String)
    zslx_name = db.Column(db.String)
    local_batch_name = db.Column(db.String)
    sg_fxk = db.Column(db.String)
    sg_sxk = db.Column(db.String)
    sg_type = db.Column(db.String)
    sg_name = db.Column(db.String)
    sg_info = db.Column(db.String)
    sg_xuanke = db.Column(db.String)
    range_max_rank = db.Column(db.String)

    def as_dict(self):
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}
    